#include "esc_spi.h"
#include "spi_slave.h"
#include "stm32f1xx_hal.h"
#include "tim.h"
#include <string.h>

static int16_t throttles[ESC_CHANNELS];
static uint32_t last_frame_ms = 0;

/* Simple ms tick provider: user should call ESC_TimeoutHandler each ms with incrementing ms */


/* Simple CRC8 (poly 0x07) */
static uint8_t crc8(const uint8_t *buf, uint16_t len)
{
    uint8_t crc = 0;
    for (uint16_t i = 0; i < len; ++i) {
        crc ^= buf[i];
        for (int j = 0; j < 8; ++j) {
            if (crc & 0x80) crc = (crc << 1) ^ 0x07;
            else crc <<= 1;
        }
    }
    return crc;
}

void ESC_UpdateFromBuffer(uint8_t *buf, uint16_t len)
{
    if (len < 4) return;
    debug_esc_last_crc_ok = 0;
    debug_esc_last_frame_valid = 0;
    if (buf[0] != 0xAA) return;
    uint8_t cmd = buf[1];
    debug_esc_last_cmd = cmd;
    uint8_t dlen = buf[2];
    debug_esc_last_frame_len = len;
    if (dlen + 4 > len) return;
    uint8_t crc = buf[len-1];
    debug_esc_last_crc = crc;
    if (crc8(buf, len-1) != crc) return;
    debug_esc_last_crc_ok = 1;

    if (cmd == 0x01 && dlen == ESC_CHANNELS * 2) {
        for (int i = 0; i < ESC_CHANNELS; ++i) {
            int16_t v = (int16_t)(buf[3 + i*2] | (buf[3 + i*2 +1] << 8));
            throttles[i] = v;
            debug_esc_throttles[i] = v;
        }
        /* update last frame time (simple HAL_GetTick fallback if available) */
        last_frame_ms = HAL_GetTick();
        debug_esc_last_frame_valid = 1;
        debug_esc_last_frame_ms = last_frame_ms;
    }
}

int16_t ESC_GetThrottle(int idx)
{
    if (idx < 0 || idx >= ESC_CHANNELS) return 0;
    return throttles[idx];
}

/* Minimal SPI slave init using HAL SPI in interrupt mode on SPI2 (PB13-SCK, PB14-MISO, PB15-MOSI)
   For simplicity we use polling/interrupt reception of bytes in a small buffer. This requires
   user to call HAL_SPI_Receive_IT or similar; here we'll provide ESC_SPI_Init to configure SPI2.
*/

void ESC_SPI_Init(void)
{
    /* Implementation note: SPI2 configuration is generated by CubeMX in spi.c if present.
       If not, user should ensure SPI2 is enabled as slave, CPOL=0, CPHA=0, 8-bit, and NVIC for SPI2.
       Here we only zero the throttle array and rely on existing MX_SPI2_Init if available. */
    for (int i = 0; i < ESC_CHANNELS; ++i) throttles[i] = 0;

     /* SPI slave init is performed by the application startup (System_Init in App.c).
         Avoid initializing SPI twice here, which can reset the ongoing IT transfer. */
}

/* Helper: apply throttle to TIM PWM outputs. Map throttles (assumed -100..100) to pulse width 1ms..2ms (1000..2000us)
   and set CCR of TIM2 (CH1-4), TIM3 (CH1-2), TIM4 (CH1-4) accordingly to cover 8 channels.
*/
void ESC_ApplyToPWM(void)
{
    /* 8 路 PWM 输出：TIM1 CH1-CH4 + TIM2 CH1-CH4（1us tick / 50Hz） */
    uint32_t pulse_us;
    for (int i = 0; i < ESC_CHANNELS; ++i) {
        int16_t v = throttles[i];
        /* 支持两种输入：-100..100 百分比 或 1000..2000us 直接脉宽 */
        if (v >= -100 && v <= 100) {
            pulse_us = (uint32_t)(1500 + (v * 5));
        } else {
            pulse_us = (uint32_t)v;
        }
        if (pulse_us < 1000) pulse_us = 1000;
        if (pulse_us > 2000) pulse_us = 2000;

        if (i < 4) {
            uint32_t ch = (i == 0) ? TIM_CHANNEL_1 : (i == 1) ? TIM_CHANNEL_2 : (i == 2) ? TIM_CHANNEL_3 : TIM_CHANNEL_4;
            __HAL_TIM_SET_COMPARE(&htim1, ch, pulse_us);
        } else {
            uint32_t ch = (i == 4) ? TIM_CHANNEL_1 : (i == 5) ? TIM_CHANNEL_2 : (i == 6) ? TIM_CHANNEL_3 : TIM_CHANNEL_4;
            __HAL_TIM_SET_COMPARE(&htim2, ch, pulse_us);
        }
    }
}

void ESC_TimeoutHandler(uint32_t timeout_ms)
{
    uint32_t now = HAL_GetTick();
    if (now - last_frame_ms > timeout_ms) {
        debug_esc_timeout_active = 1;
        /* reset to mid (0 -> 1500us mapping) */
        for (int i = 0; i < ESC_CHANNELS; ++i) throttles[i] = 0;
        /* immediately apply to PWM to ensure safe state */
        ESC_ApplyToPWM();
    } else {
        debug_esc_timeout_active = 0;
    }
}
